name: Terraform create GCP bucket

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4 

    
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: |
        cd $GITHUB_WORKSPACE
        terraform apply -auto-approve
      env:
        TF_VAR_credentials_file: ${{ secrets.GCP_SA_KEY }}
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: "europe-west3" 
        TF_VAR_bucket_name: "data_bucket"  
