name: Solar Power Prediction CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight UTC

jobs:
  terraform_deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.4 

      - uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/terraform

      - name: Terraform Apply
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${{ github.workspace }}/terraform/reflected-oath-405515-70b04b6190ad.json
          terraform apply -auto-approve -var="my_gcs_bucket=data_bucket_raw" -var="my_gcs_bucket2=data_bucket_processed"
        env:
          TF_VAR_credentials_file: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: "europe-west3" 
        working-directory: ${{ github.workspace }}/terraform

  load_data:
    if: github.event_name == 'schedule'
    needs: terraform_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies for task1
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load energy data
        run: load_energy_data.py

      - name: Load weather data
        run: load_weather_data.py

  build_and_run:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule'
    needs:
      - terraform_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode and save GCP_SA_KEY
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${{ github.workspace }}/terraform/reflected-oath-405515-70b04b6190ad.json

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Load Weather Data
        run: python load_weather_data.py

      - name: Load Energy Data
        run: python load_energy_data.py

      - name: Preprocess Data
        run: python preprocess_data.py

      - name: Run Main Script
        run: python run_main.py
