name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

      env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/terraform/reflected-oath-405515-70b04b6190ad.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Load Weather Data
      run: python load_weather_data.py

    - name: Load Energy Data
      run: python load_energy_data.py

    - name: Preprocess Data
      run: python preprocess_data.py

    - name: Run Main Script
      run: python run_main.py
